import { useState } from "react";
import type { MergePreview } from "./types";

interface Props { preview: MergePreview; busy?: boolean; onCancel: () => void; onFixWithAi: () => Promise<{ context: Record<string, "target" | "source">; workspace: Record<string, "target" | "source">; aiDecisions: Record<string, string> }>; onMerge: (resolution: { workspace: Record<string, "target" | "source" | "ai">; context: Record<string, "target" | "source" | "ai"> }) => void; }

export function MergeReview({ preview, busy = false, onCancel, onFixWithAi, onMerge }: Props) {
  const [workspace, setWorkspace] = useState<Record<string, "target" | "source" | "ai">>(() => Object.fromEntries(preview.workspaceConflicts.map((item) => [item.path, "ai"] as const)));
  const [context, setContext] = useState<Record<string, "target" | "source" | "ai">>(() => Object.fromEntries(preview.contextConflicts.map((item) => [item.id, "ai"] as const)));
  const [aiBusy, setAiBusy] = useState<string | null>(null);
  const [aiError, setAiError] = useState<string | null>(null);
  const [aiResolved, setAiResolved] = useState<Set<string>>(new Set());
  const [aiDecisions, setAiDecisions] = useState<Record<string, { choice: "target" | "source"; explanation: string }>>({});
  const selectContext = (conflictId: string, choice: "target" | "source") => {
    setContext((current) => ({ ...current, [conflictId]: choice }));
    const semantic = preview.workspaceConflicts.find((item) => item.path.startsWith("semantic:"));
    if (semantic) {
      const relatedPaths = new Set([semantic.path, ...(choice === "target" ? semantic.targetPaths ?? [] : semantic.sourcePaths ?? [])]);
      setWorkspace((current) => Object.fromEntries(Object.entries(current).map(([path, currentChoice]) => [path, relatedPaths.has(path) ? choice : currentChoice])));
    }
  };
  const fixWithAi = async (conflictKey?: string) => { setAiBusy(conflictKey ?? "all"); setAiError(null); try { const resolved = await onFixWithAi(); if (conflictKey?.startsWith("workspace:")) { const conflictPath = conflictKey.slice("workspace:".length); if (resolved.workspace[conflictPath]) { setWorkspace((current) => ({ ...current, [conflictPath]: resolved.workspace[conflictPath] })); setAiResolved((current) => new Set(current).add(conflictKey)); setAiDecisions((current) => ({ ...current, [conflictKey]: { choice: resolved.workspace[conflictPath]!, explanation: resolved.aiDecisions[conflictKey] ?? "AI selected this implementation based on the combined merge criteria." } })); } } else if (conflictKey?.startsWith("context:")) { const conflictId = conflictKey.slice("context:".length); if (resolved.context[conflictId]) { setContext((current) => ({ ...current, [conflictId]: resolved.context[conflictId] })); setAiResolved((current) => new Set(current).add(conflictKey)); setAiDecisions((current) => ({ ...current, [conflictKey]: { choice: resolved.context[conflictId]!, explanation: resolved.aiDecisions[conflictKey] ?? "AI selected this prompt based on the combined merge criteria." } })); } } else { setWorkspace((current) => ({ ...current, ...resolved.workspace })); setContext((current) => ({ ...current, ...resolved.context })); setAiResolved((current) => new Set([...current, ...preview.workspaceConflicts.map((item) => "workspace:" + item.path), ...preview.contextConflicts.map((item) => "context:" + item.id)])); setAiDecisions((current) => ({ ...current, ...Object.fromEntries(Object.entries(resolved.workspace).map(([key, value]) => ["workspace:" + key, { choice: value, explanation: resolved.aiDecisions["workspace:" + key] ?? "AI selected this implementation based on the combined merge criteria." }])), ...Object.fromEntries(Object.entries(resolved.context).map(([key, value]) => ["context:" + key, { choice: value, explanation: resolved.aiDecisions["context:" + key] ?? "AI selected this prompt based on the combined merge criteria." }])) })); } } catch (reason) { setAiError(reason instanceof Error ? reason.message : String(reason)); } finally { setAiBusy(null); } };
  return <div className="modal-backdrop" onMouseDown={onCancel}>
    <section className="modal checkpoint-overlay merge-overlay" onMouseDown={(event) => event.stopPropagation()}>
      <div className="modal-heading"><div><span className="eyebrow">Strict merge review</span><h2>Combine both outcomes</h2></div><button type="button" onClick={onCancel}>×</button></div>
      <div className="merge-outcomes"><article className="merge-outcome-card target"><span className="merge-card-kicker">TARGET · MAIN</span><h3>{preview.target.label}</h3><p className="merge-summary">{preview.target.summary}</p><ul className="merge-outcome-details">{preview.target.details.slice(1).map((item) => <li key={item}>{item}</li>)}</ul></article><article className="merge-outcome-card source"><span className="merge-card-kicker">SOURCE · BRANCH</span><h3>{preview.source.label}</h3><p className="merge-summary">{preview.source.summary}</p><ul className="merge-outcome-details">{preview.source.details.slice(1).map((item) => <li key={item}>{item}</li>)}</ul></article></div>
      <section className="merge-criteria"><div><span className="merge-card-kicker">MERGE CONTRACT</span><h3>Combined acceptance criteria</h3></div><ul>{preview.acceptanceCriteria.map((item) => <li key={item}>{item}</li>)}</ul></section>
      {aiResolved.size > 0 && <p className="merge-ai-resolved" role="status">✓ {aiResolved.size} conflict{aiResolved.size === 1 ? "" : "s"} resolved with AI</p>}
      {Object.keys(aiDecisions).length > 0 && <section className="merge-ai-results"><span className="merge-card-kicker">AI REVIEW RESULT</span><h3>What AI changed</h3><ul>{Object.entries(aiDecisions).map(([key, decision]) => <li key={key}><span>{key.replace(/^(workspace:|context:)/, "")}</span><div><strong>{decision.choice === "target" ? "Kept target/main" : "Kept source/branch"}</strong><small>{decision.explanation}</small></div></li>)}</ul></section>}
      {preview.workspaceConflicts.filter((item) => !aiResolved.has("workspace:" + item.path)).length > 0 && <section className="merge-section"><div><span className="merge-card-kicker">NEEDS DECISION</span><h3>Workspace conflicts</h3><p className="inspection-muted">Choose an implementation or let AI evaluate the complete workspace context.</p></div>{preview.workspaceConflicts.filter((item) => !aiResolved.has("workspace:" + item.path)).map((item) => <div className="merge-conflict-choice" key={item.path}><span className="merge-file-path">{item.path}</span><select value={workspace[item.path] ?? "ai"} onChange={(event) => setWorkspace((current) => ({ ...current, [item.path]: event.target.value as "target" | "source" | "ai" }))}><option value="ai">✦ Fix with AI</option><option value="target">Keep target/main</option><option value="source">Keep source/branch</option></select><button className="button button-ghost" type="button" disabled={aiBusy !== null} onClick={() => void fixWithAi("workspace:" + item.path)}>{aiBusy === "workspace:" + item.path ? "AI is reviewing…" : "✦ Fix with AI"}</button></div>)}</section>}
      {preview.contextConflicts.filter((item) => !aiResolved.has("context:" + item.id)).length > 0 && <section className="merge-section"><div><span className="merge-card-kicker">NEEDS DECISION</span><h3>Conversation conflicts</h3><p className="inspection-muted">The selected prompt and response are retained together.</p></div>{preview.contextConflicts.filter((item) => !aiResolved.has("context:" + item.id)).map((item) => <div className="context-conflict" key={item.id}><label><input type="radio" name={item.id} checked={context[item.id] === "target"} onChange={() => selectContext(item.id, "target")} /><span><b>Target / main{item.targetDeleted ? " (deleted)" : ""}</b>{item.target.prompt}<small>{item.target.response ?? "No response recorded"}</small></span></label><label><input type="radio" name={item.id} checked={context[item.id] === "source"} onChange={() => selectContext(item.id, "source")} /><span><b>Source / branch{item.sourceDeleted ? " (deleted)" : ""}</b>{item.source.prompt}<small>{item.source.response ?? "No response recorded"}</small></span></label><button className="button button-ghost" type="button" disabled={aiBusy !== null} onClick={() => void fixWithAi("context:" + item.id)}>{aiBusy === "context:" + item.id ? "AI is reviewing…" : "✦ Fix with AI"}</button>{context[item.id] === "ai" && <small>AI recommendation selected. It evaluates the complete outcomes, criteria, workspace, and prompts in an isolated session.</small>}</div>)}</section>}
      {aiError && <p className="form-error">AI resolution failed: {aiError}</p>}<div className="modal-actions"><button className="button button-ghost" type="button" disabled={busy || aiBusy !== null} onClick={onCancel}>Cancel</button><button className="button button-secondary" type="button" disabled={busy || aiBusy !== null} onClick={() => void fixWithAi()}>{aiBusy === "all" ? <><span className="spinner" /> AI is reviewing…</> : "✦ Fix all with AI"}</button><button className="button button-primary" type="button" disabled={busy || aiBusy !== null} onClick={() => onMerge({ workspace, context })}>{busy ? <><span className="spinner" /> Merging…</> : "Merge into main"}</button></div>
    </section>
  </div>;
}
