import { useState } from "react";
import type { MergePreview } from "./types";

interface Props { preview: MergePreview; busy?: boolean; onCancel: () => void; onMerge: (resolution: { workspace: Record<string, "target" | "source" | "ai">; context: Record<string, "target" | "source" | "ai"> }) => void; }

export function MergeReview({ preview, busy = false, onCancel, onMerge }: Props) {
  const [workspace, setWorkspace] = useState<Record<string, "target" | "source" | "ai">>(() => Object.fromEntries(preview.workspaceConflicts.map((item) => [item.path, "ai"] as const)));
  const [context, setContext] = useState<Record<string, "target" | "source" | "ai">>(() => Object.fromEntries(preview.contextConflicts.map((item) => [item.id, "ai"] as const)));
  return <div className="modal-backdrop" onMouseDown={onCancel}>
    <section className="modal checkpoint-overlay merge-overlay" onMouseDown={(event) => event.stopPropagation()}>
      <div className="modal-heading"><div><span className="eyebrow">Strict merge review</span><h2>Combine both outcomes</h2></div><button type="button" onClick={onCancel}>×</button></div>
      <div className="merge-outcomes"><article className="merge-outcome-card target"><span className="merge-card-kicker">TARGET · MAIN</span><h3>{preview.target.label}</h3><p className="merge-summary">{preview.target.summary}</p><ul className="merge-outcome-details">{preview.target.details.map((item) => <li key={item}>{item}</li>)}</ul></article><article className="merge-outcome-card source"><span className="merge-card-kicker">SOURCE · BRANCH</span><h3>{preview.source.label}</h3><p className="merge-summary">{preview.source.summary}</p><ul className="merge-outcome-details">{preview.source.details.map((item) => <li key={item}>{item}</li>)}</ul></article></div>
      <section className="merge-criteria"><div><span className="merge-card-kicker">MERGE CONTRACT</span><h3>Combined acceptance criteria</h3></div><ul>{preview.acceptanceCriteria.map((item) => <li key={item}>{item}</li>)}</ul></section>
      {preview.workspaceConflicts.length > 0 && <section className="merge-section"><div><span className="merge-card-kicker">NEEDS DECISION</span><h3>Workspace conflicts</h3><p className="inspection-muted">Choose an implementation or let AI evaluate the complete workspace context.</p></div>{preview.workspaceConflicts.map((item) => <label key={item.path}><span className="merge-file-path">{item.path}</span><select value={workspace[item.path] ?? "ai"} onChange={(event) => setWorkspace((current) => ({ ...current, [item.path]: event.target.value as "target" | "source" | "ai" }))}><option value="ai">✦ Fix with AI</option><option value="target">Keep target/main</option><option value="source">Keep source/branch</option></select></label>)}</section>}
      {preview.contextConflicts.length > 0 && <section className="merge-section"><div><span className="merge-card-kicker">NEEDS DECISION</span><h3>Context prompt conflicts</h3><p className="inspection-muted">Only the selected prompt is retained.</p></div>{preview.contextConflicts.map((item) => <div className="context-conflict" key={item.id}><label><input type="radio" name={item.id} checked={context[item.id] === "target"} onChange={() => setContext((current) => ({ ...current, [item.id]: "target" }))} /><span><b>Target prompt</b>{item.targetPrompt}</span></label><label><input type="radio" name={item.id} checked={context[item.id] === "source"} onChange={() => setContext((current) => ({ ...current, [item.id]: "source" }))} /><span><b>Source prompt</b>{item.sourcePrompt}</span></label><button className="button button-ghost" type="button" onClick={() => setContext((current) => ({ ...current, [item.id]: "ai" }))}>✦ Fix with AI</button>{context[item.id] === "ai" && <small>AI will evaluate the complete outcomes, criteria, workspace, and prompts in an isolated session.</small>}</div>)}</section>}
      <div className="modal-actions"><button className="button button-ghost" type="button" onClick={onCancel}>Cancel</button><button className="button button-primary" type="button" disabled={busy} onClick={() => onMerge({ workspace, context })}>{busy ? "Merging…" : "Merge into main"}</button></div>
    </section>
  </div>;
}
